rabbitmq:
  direct:
    exchange: test.direct
    queue: test.direct.queue
    routingKey: test.routingKey
  fanout:
    exchange: test.fanout
  topic:
    exchange: test.topic
    routingKey: '*.routingKey.topic'
    routingKey2: '#.topic'
    queue: test.topic.queue
  header:
    exchange: test.header
    queue: test.header.queue

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    port: 5672

server:
  port: 8080